 // Source code is unavailable, and was generated by the Fernflower decompiler.
package codigo;

import java.io.Serializable;

public class Producto implements Serializable {
   private static final long serialVersionUID = 1L;
   private int id;
   private String descripcion;
   private double precio;
   private int stock;

   public Producto(int id, String descripcion, double precio, int stock) {
      this.id = id;
      this.descripcion = descripcion;
      this.precio = precio;
      this.stock = stock;
   }

   public int getId() {
      return this.id;
   }

   public void setId(int id) {
      this.id = id;
   }

   public String getDescripcion() {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion) {
      this.descripcion = descripcion;
   }

   public double getPrecio() {
      return this.precio;
   }

   public void setPrecio(double precio) {
      this.precio = precio;
   }

   public int getStock() {
      return this.stock;
   }

   public void setStock(int stock) {
      if (stock >= 0) {
         this.stock = stock;
      } else {
         throw new IllegalArgumentException("El stock no puede ser menor a 0.");
      }
   }

   public String toString() {
      return this.descripcion + " (ID: " + this.id + ", Precio: " + this.precio + ", Stock: " + this.stock + ")";
   }
}
