 // Source code is unavailable, and was generated by the Fernflower decompiler.
package codigo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Venta implements Serializable {
   private static final long serialVersionUID = 1L;
   private int id;
   private List<Producto> productos;
   private Date fecha;
   private double total;

   public Venta(int id) {
      this.id = id;
      this.productos = new ArrayList();
      this.fecha = new Date();
      this.total = 0.0D;
   }

   public void agregarProducto(Producto producto, int cantidadVendida) {
      Producto productoVendido = new Producto(producto.getId(), producto.getDescripcion(), producto.getPrecio(), cantidadVendida);
      this.productos.add(productoVendido);
      this.total += productoVendido.getPrecio() * (double)cantidadVendida;
   }

   public int getId() {
      return this.id;
   }

   public List<Producto> getProductos() {
      return this.productos;
   }

   public Date getFecha() {
      return this.fecha;
   }

   public double getTotal() {
      return this.total;
   }

   public String toString() {
      StringBuilder sb = new StringBuilder();
      Iterator var3 = this.productos.iterator();

      while(var3.hasNext()) {
         Producto producto = (Producto)var3.next();
         sb.append(producto.getDescripcion()).append(" x ").append(producto.getStock()).append(", ");
      }

      return sb.toString();
   }
}
